#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActiveModifiersPanelContent

#include "Basic.hpp"


namespace SDK::Params
{

// Function ActiveModifiersPanelContent.ActiveModifiersPanelContent_C.Init
// 0x0010 (0x0010 - 0x0000)
struct ActiveModifiersPanelContent_C_Init final
{
public:
	TArray<class UFortGameplayModifierItemDefinition*> InModifiers;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(ActiveModifiersPanelContent_C_Init) == 0x000008, "Wrong alignment on ActiveModifiersPanelContent_C_Init");
static_assert(sizeof(ActiveModifiersPanelContent_C_Init) == 0x000010, "Wrong size on ActiveModifiersPanelContent_C_Init");
static_assert(offsetof(ActiveModifiersPanelContent_C_Init, InModifiers) == 0x000000, "Member 'ActiveModifiersPanelContent_C_Init::InModifiers' has a wrong offset!");

}

