#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Announce_WinterCine

#include "Basic.hpp"

#include "Announce_EventCine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Announce_WinterCine.Announce_WinterCine_C
// 0x0000 (0x0400 - 0x0400)
class AAnnounce_WinterCine_C final : public AAnnounce_EventCine_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Announce_WinterCine_C">();
	}
	static class AAnnounce_WinterCine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAnnounce_WinterCine_C>();
	}
};
static_assert(alignof(AAnnounce_WinterCine_C) == 0x000008, "Wrong alignment on AAnnounce_WinterCine_C");
static_assert(sizeof(AAnnounce_WinterCine_C) == 0x000400, "Wrong size on AAnnounce_WinterCine_C");

}

