#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_Grad_Free

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border_Grad_Free.Border_Grad_Free_C
// 0x0000 (0x00A0 - 0x00A0)
class UBorder_Grad_Free_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border_Grad_Free_C">();
	}
	static class UBorder_Grad_Free_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_Grad_Free_C>();
	}
};
static_assert(alignof(UBorder_Grad_Free_C) == 0x000008, "Wrong alignment on UBorder_Grad_Free_C");
static_assert(sizeof(UBorder_Grad_Free_C) == 0x0000A0, "Wrong size on UBorder_Grad_Free_C");

}

