#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemDetailsHeaderItemDisplayText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemDetailsHeaderItemDisplayText.ItemDetailsHeaderItemDisplayText_C
// 0x0010 (0x0268 - 0x0258)
class UItemDetailsHeaderItemDisplayText_C final : public UFortItemDetailElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0258(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       ItemDisplayName;                                   // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ItemDetailsHeaderItemDisplayText(int32 EntryPoint);
	void HandlePostDifferentItemToCompareWithSet();
	void HandlePostDifferentItemToDetailSet();
	void GetDisplayName(class FText* DisplayName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemDetailsHeaderItemDisplayText_C">();
	}
	static class UItemDetailsHeaderItemDisplayText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemDetailsHeaderItemDisplayText_C>();
	}
};
static_assert(alignof(UItemDetailsHeaderItemDisplayText_C) == 0x000008, "Wrong alignment on UItemDetailsHeaderItemDisplayText_C");
static_assert(sizeof(UItemDetailsHeaderItemDisplayText_C) == 0x000268, "Wrong size on UItemDetailsHeaderItemDisplayText_C");
static_assert(offsetof(UItemDetailsHeaderItemDisplayText_C, UberGraphFrame) == 0x000258, "Member 'UItemDetailsHeaderItemDisplayText_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UItemDetailsHeaderItemDisplayText_C, ItemDisplayName) == 0x000260, "Member 'UItemDetailsHeaderItemDisplayText_C::ItemDisplayName' has a wrong offset!");

}

