#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestTrackerEntry

#include "Basic.hpp"


namespace SDK::Params
{

// Function QuestTrackerEntry.QuestTrackerEntry_C.ExecuteUbergraph_QuestTrackerEntry
// 0x0004 (0x0004 - 0x0000)
struct QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry) == 0x000004, "Wrong alignment on QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry");
static_assert(sizeof(QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry) == 0x000004, "Wrong size on QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry");
static_assert(offsetof(QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry, EntryPoint) == 0x000000, "Member 'QuestTrackerEntry_C_ExecuteUbergraph_QuestTrackerEntry::EntryPoint' has a wrong offset!");

}

