#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SurvivorRescuedCounter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SurvivorRescuedCounter.SurvivorRescuedCounter_C
// 0x0010 (0x0220 - 0x0210)
class USurvivorRescuedCounter_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0210(0x0008)(Transient, DuplicateTransient)
	class UCommonNumericTextBlock*                NumberSurvivors;                                   // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SurvivorRescuedCounter(int32 EntryPoint);
	void Construct();
	void UpdateSurvivorsRescued(int32 SurvivorsRescued);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SurvivorRescuedCounter_C">();
	}
	static class USurvivorRescuedCounter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USurvivorRescuedCounter_C>();
	}
};
static_assert(alignof(USurvivorRescuedCounter_C) == 0x000008, "Wrong alignment on USurvivorRescuedCounter_C");
static_assert(sizeof(USurvivorRescuedCounter_C) == 0x000220, "Wrong size on USurvivorRescuedCounter_C");
static_assert(offsetof(USurvivorRescuedCounter_C, UberGraphFrame) == 0x000210, "Member 'USurvivorRescuedCounter_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USurvivorRescuedCounter_C, NumberSurvivors) == 0x000218, "Member 'USurvivorRescuedCounter_C::NumberSurvivors' has a wrong offset!");

}

