#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DailyQuestWidget

#include "Basic.hpp"

#include "DailyQuestWidget_classes.hpp"
#include "DailyQuestWidget_parameters.hpp"


namespace SDK
{

// Function DailyQuestWidget.DailyQuestWidget_C.SetQuestItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortQuestItem*                   Param_Quest                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDailyQuestWidget_C::SetQuestItem(class UFortQuestItem* Param_Quest)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DailyQuestWidget_C", "SetQuestItem");

	Params::DailyQuestWidget_C_SetQuestItem Parms{};

	Parms.Param_Quest = Param_Quest;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DailyQuestWidget.DailyQuestWidget_C.FilterObjectives
// (Public, BlueprintCallable, BlueprintEvent)

void UDailyQuestWidget_C::FilterObjectives()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DailyQuestWidget_C", "FilterObjectives");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DailyQuestWidget.DailyQuestWidget_C.UpdateObjectiveWidgets
// (Public, BlueprintCallable, BlueprintEvent)

void UDailyQuestWidget_C::UpdateObjectiveWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DailyQuestWidget_C", "UpdateObjectiveWidgets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DailyQuestWidget.DailyQuestWidget_C.CreateAllObjectiveWidgets
// (Public, BlueprintCallable, BlueprintEvent)

void UDailyQuestWidget_C::CreateAllObjectiveWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DailyQuestWidget_C", "CreateAllObjectiveWidgets");

	UObject::ProcessEvent(Func, nullptr);
}

}

