#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemView

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ItemView.ItemView_C
// 0x0000 (0x02F0 - 0x02F0)
class UItemView_C final : public UFortItemView
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemView_C">();
	}
	static class UItemView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemView_C>();
	}
};
static_assert(alignof(UItemView_C) == 0x000008, "Wrong alignment on UItemView_C");
static_assert(sizeof(UItemView_C) == 0x0002F0, "Wrong size on UItemView_C");

}

