#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionObjectiveProgressBarsManager

#include "Basic.hpp"

#include "MissionObjectiveProgressBarsManager_classes.hpp"
#include "MissionObjectiveProgressBarsManager_parameters.hpp"


namespace SDK
{

// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.UpdateObjectiveProgressBars
// (Public, BlueprintCallable, BlueprintEvent)

void UMissionObjectiveProgressBarsManager_C::UpdateObjectiveProgressBars()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "UpdateObjectiveProgressBars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortObjectiveBase*               Param_TrackedObjective                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInConfigureAsHUD                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMissionObjectiveProgressBarsManager_C::Setup(class AFortObjectiveBase* Param_TrackedObjective, bool bInConfigureAsHUD)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "Setup");

	Params::MissionObjectiveProgressBarsManager_C_Setup Parms{};

	Parms.Param_TrackedObjective = Param_TrackedObjective;
	Parms.bInConfigureAsHUD = bInConfigureAsHUD;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.CreateProgressBarWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionObjectiveProgressBarsManager_C::CreateProgressBarWidget(int32 Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "CreateProgressBarWidget");

	Params::MissionObjectiveProgressBarsManager_C_CreateProgressBarWidget Parms{};

	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.HandleObjectiveStatusChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortObjectiveBase*               Objective                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortObjectiveStatus                    New_Status                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionObjectiveProgressBarsManager_C::HandleObjectiveStatusChanged(class AFortObjectiveBase* Objective, EFortObjectiveStatus New_Status)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "HandleObjectiveStatusChanged");

	Params::MissionObjectiveProgressBarsManager_C_HandleObjectiveStatusChanged Parms{};

	Parms.Objective = Objective;
	Parms.New_Status = New_Status;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.HandleObjectiveVisibilityChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortObjectiveBase*               Objective                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    New_Visibility                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMissionObjectiveProgressBarsManager_C::HandleObjectiveVisibilityChanged(class AFortObjectiveBase* Objective, bool New_Visibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "HandleObjectiveVisibilityChanged");

	Params::MissionObjectiveProgressBarsManager_C_HandleObjectiveVisibilityChanged Parms{};

	Parms.Objective = Objective;
	Parms.New_Visibility = New_Visibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.HandleUpdate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortMissionState*                Objective                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionObjectiveProgressBarsManager_C::HandleUpdate(class AFortMissionState* Objective)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "HandleUpdate");

	Params::MissionObjectiveProgressBarsManager_C_HandleUpdate Parms{};

	Parms.Objective = Objective;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionObjectiveProgressBarsManager.MissionObjectiveProgressBarsManager_C.GetHeightEstimate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Height                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionObjectiveProgressBarsManager_C::GetHeightEstimate(float* Height)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionObjectiveProgressBarsManager_C", "GetHeightEstimate");

	Params::MissionObjectiveProgressBarsManager_C_GetHeightEstimate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Height != nullptr)
		*Height = Parms.Height;
}

}

