#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StorePinataMaster_Parent

#include "Basic.hpp"


namespace SDK::Params
{

// Function StorePinataMaster_Parent.StorePinataMaster_Parent_C.ExecuteUbergraph_StorePinataMaster_Parent
// 0x0004 (0x0004 - 0x0000)
struct StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent) == 0x000004, "Wrong alignment on StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent");
static_assert(sizeof(StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent) == 0x000004, "Wrong size on StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent");
static_assert(offsetof(StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent, EntryPoint) == 0x000000, "Member 'StorePinataMaster_Parent_C_ExecuteUbergraph_StorePinataMaster_Parent::EntryPoint' has a wrong offset!");

}

