#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusHeaderMinusLMinusHorizon

#include "Basic.hpp"

#include "TextStyleMinusHeaderParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Header-L-Horizon.TextStyle-Header-L-Horizon_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusHeaderMinusLMinusHorizon_C final : public UTextStyleMinusHeaderParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Header-L-Horizon_C">();
	}
	static class UTextStyleMinusHeaderMinusLMinusHorizon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusHeaderMinusLMinusHorizon_C>();
	}
};
static_assert(alignof(UTextStyleMinusHeaderMinusLMinusHorizon_C) == 0x000008, "Wrong alignment on UTextStyleMinusHeaderMinusLMinusHorizon_C");
static_assert(sizeof(UTextStyleMinusHeaderMinusLMinusHorizon_C) == 0x0000C0, "Wrong size on UTextStyleMinusHeaderMinusLMinusHorizon_C");

}

